version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  orders_db:
    image: postgres
    container_name: orders_db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - orders_data:/var/lib/orders_data
    ports:
      - "5432:5432"

  products_db:
    image: postgres
    container_name: products_db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - products_data:/var/lib/products_data
    ports:
      - "5433:5432"

  users_db:
    image: postgres
    container_name: users_db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - users_data:/var/lib/users_data
    ports:
      - "5434:5432"

  orders_service:
    build:
      context: ./services/orders_service
    container_name: orders_service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./services/orders_service:/app/
    ports:
      - "8000:8000"
    environment:
      - ORDERS_POSTGRES_NAME=postgres
      - ORDERS_POSTGRES_USER=postgres
      - ORDERS_POSTGRES_PASSWORD=postgres
      - ORDERS_POSTGRES_HOST=orders_db
      - ORDERS_POSTGRES_PORT=5432
      - SECRET_KEY=secret
      - DEBUG=1
      - ALLOWED_HOSTS=*
    depends_on:
      - rabbitmq
      - orders_db

  products_service:
    build:
      context: ./services/products_service
    container_name: products_service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./services/products_service:/app/
    ports:
      - "8001:8001"
    environment:
      - PRODUCTS_POSTGRES_NAME=postgres
      - PRODUCTS_POSTGRES_USER=postgres
      - PRODUCTS_POSTGRES_PASSWORD=postgres
      - PRODUCTS_POSTGRES_HOST=products_db
      - PRODUCTS_POSTGRES_PORT=5432
      - SECRET_KEY=secret
      - DEBUG=1
      - ALLOWED_HOSTS=*
    depends_on:
      - rabbitmq
      - products_db

  users_service:
    build:
      context: ./services/users_service
    container_name: users_service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    volumes:
      - ./services/users_service:/app/
    ports:
      - "8002:8002"
    environment:
      - USERS_POSTGRES_NAME=postgres
      - USERS_POSTGRES_USER=postgres
      - USERS_POSTGRES_PASSWORD=postgres
      - USERS_POSTGRES_HOST=users_db
      - USERS_POSTGRES_PORT=5432
      - SECRET_KEY=secret
      - DEBUG=1
      - ALLOWED_HOSTS=*
    depends_on:
      - rabbitmq
      - users_db

  auth_queue:
    build:
      context: ./services/users_service
    container_name: auth_queue
    command: "python manage.py auth_queue"
    volumes:
      - ./services/users_service:/app/
    environment:
      - USERS_POSTGRES_NAME=postgres
      - USERS_POSTGRES_USER=postgres
      - USERS_POSTGRES_PASSWORD=postgres
      - USERS_POSTGRES_HOST=users_db
      - USERS_POSTGRES_PORT=5432
      - SECRET_KEY=secret
      - DEBUG=1
      - ALLOWED_HOSTS=*
    depends_on:
      - rabbitmq
      - users_db
      - users_service
         
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    command: "python manage.py runserver 0.0.0.0:80"
    volumes:
      - ./gateway:/app/
    ports:
      - "80:80"
    environment:
      - SECRET_KEY=secret
      - DEBUG=1
      - ALLOWED_HOSTS=*
      - CORS_ORIGIN_WHITELIST=http://localhost
    depends_on:
      - rabbitmq
      - users_db   

volumes:
  rabbitmq_data:
  orders_data:
  products_data:
  users_data: